### ISSUE TITLE
crossdomain.xml not found (404)

### ISSUE THREAD

**Issue by aguywithanidea** [Rhapsody/rhapsody.js#7]
Steps to reproduce:

1. Ensure the `playevent` callback will be logged to the console.
2. Start playing a track via `Rhapsody.player.play(TRACK_ID)`
3. Monitor the javascript console.

When track begins playing and the `ReadyToPlay` code is sent to the `playevent` callback, you'll notice that immediately afterwards a 404 error is thrown regarding the file `http://app.rhapsody.om/crossdomain.xml` 

![crossdomain_error](https://cloud.githubusercontent.com/assets/1666864/6989342/28c9ef76-da0f-11e4-9534-381403178026.png)

Additionally, calling the player via `https` does not cause the crossdomain.xml (or other required `xml` files) to be loaded over https.

**Comment by dudaski** [comment]
The latest release should take care of this issue
