### ISSUE TITLE
Works with Napster?

### ISSUE THREAD

**Issue by antoniojunyor** [Rhapsody/rhapsody.js#9]
Hi people,
I want to know if the rhapsode.js works with Napster app, the developer documentation not makes this clear.

**Comment by tgraham-rhapsody** [comment]
Hi,

Yes, the JS SDK will function with Napster accounts as well. We operate as
Napster in Europe and Latin America and as Rhapsody in the US.

Thanks,
~Tim

On Mon, Apr 27, 2015 at 1:38 PM, Antonio Junior <notifications@github.com>
wrote:

> Hi people,
> I want to know if the rhapsode.js works with Napster app, the developer
> documentation not makes this clear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rhapsody/rhapsody.js/issues/9>.
>



-- 

[image: signature-marks-small.png]
Tim Graham
Senior Program Manager | tgraham@rhapsody.com <tgraham@rhapsodycom>

Rhapsody <http://www.rhapsody.com/> | Napster <http://www.napster.com/>
701 Fifth Ave | Suite 3100 | Seattle | WA | 98104
O: (206) 707-8203


This message may contain information that is confidential and/or protected
by law.
If you have received this communication in error, please contact the sender
immediately and delete the message.

**Comment by antoniojunyor** [comment]
Okay @tgraham-rhapsody 
Thanks for the answer, I will test with JS SDK :metal:
